services:
  home:
    build: ./home
    container_name: home_service
    restart: always
    network_mode: "host"

  flask_app:
    build: ./stats
    container_name: flask_service
    restart: always
    privileged: true
    network_mode: "host"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # Permessi per journalctl
      - /var/log/journal:/var/log/journal:ro
      - /run/systemd/journal/socket:/run/systemd/journal/socket
      #vcgencmd
      - /usr/bin/vcgencmd:/usr/bin/vcgencmd
      - /usr/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu:ro
      # Permessi per UFW
      - /etc/ufw:/etc/ufw:ro
      - /lib/modules:/lib/modules:ro
      - /usr/sbin/iptables:/usr/sbin/iptables
      - /usr/sbin/ip6tables:/usr/sbin/ip6tables
    devices:
      - "/dev/vchiq:/dev/vchiq"

  flask_music:
    build: ./music
    container_name: music_service
    restart: always
    network_mode: "host"
    environment:
      - PYTHONUNBUFFERED=1
      - MUSIC_DIR=/music
      - DB_PATH=/data/metadata.db
    volumes:
      #path alla cartella locale con tutti gli artisti/album/canzoni
      - /${MUSIC_DIR}:/music:ro
      #file delle playlist montato a runtime
      - ./shared/db.py:/app/db.py
      - ./data:/data

  metadata-worker:
    build: ./metadata-worker
    container_name: metadata_service
    volumes:
      - ${MUSIC_DIR}:/music:ro
      - ./shared/db.py:/app/db.py
      - ./data:/data
    environment:
      - SCAN_INTERVAL=3600
      - MUSIC_DIR=/music
      - DB_PATH=/data/metadata.db
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
